export const CONSTANTS = {
  ATTACH_PHOTO_REPOSITORY: 'ATTACH_PHOTO_REPOSITORY',
  REVIEW_REPOSITORY: 'REVIEW_REPOSITORY',
  REVIEW_POINT_REPOSITORY: 'REVIEW_POINT_REPOSITORY',
  PLACE_REPOSITORY: 'PLACE_REPOSITORY',
  USER_REPOSITORY: 'USER_REPOSITORY',
  DATA_SOURCE: 'DATA_SOURCE',
};
